site_name: AHO Open Source
site_url: https://aho-opensource.github.io
site_description: Freedom for The Oslo School of Architecture and Design
site_author: karamellpelle
repo_url: https://github.com/aho-opensource/homepage
repo_name: aho-opensource/homepage

nav:
  - index.md
  - "Software":
    - software/index.md
    - "System":   software#system
    - "CAD":      software#cad
    - "Graphic":  software#graphic
    - "Video":    software#video
    - "Audio":    software#audio
    - "Web":      software#web
    - "Office":   software#office
    - "Diagram":  software#diagram
    - "Tools":    software#tools
  - "Assets":
    - assets/index.md
    - "Icons": assets#icons
    - "Fonts": assets#fonts
    - "Vectors": assets#vectors
    - "3D-models": assets#3d-models
    - "Textures": assets#textures
    - "Photos": assets#photos
    - "Sound": assets#sound
    - "Music": assets#music
    - "Data": assets#data
    #- "": assets#
  - "Study Programs":
    - programmes/architecture.md
    - programmes/design.md
    - programmes/landscape_architecture.md
  #- about.md
  #- todo.md

plugins:
  - search
  - tags
  - badges
  #- meta # this is not part of Materials Insider anymore, so add this soon
  - link-embeds:
      enabled: true
      name_default: "FIXME: no name"
      desc_default: "FIXME: no desc"
      image_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/c0298d98-0910-4235-a88f-0c3e2f704ba7"
      image_disabled: false
      favicon_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/b37da9c6-6f17-4c3f-9c94-c346a6f31bfa"
      favicon_disabled: true
      favicon_size: 25
      target: "blank"
      accent: "FFFFFF1A"
      verbose: false

#extra:  

theme:
    name: material

    logo: images/ahopen-logo.svg
    favicon: images/ahopen-favicon.svg

    features:
        - content.tabs.link # link tab selection on page
        #- content.tooltips
        - navigation.footer
        - navigation.tracker
        #- navigation.expand
        - toc.follow
        - navigation.indexes

    icon:
      #annotation: material/tooltip-text
      annotation: material/tooltip-text-outline
      #annotation: material/information
      #annotation: material/information-symbol-outline

      #admonition:
      #    note: octicons/tag-16
      #    abstract: octicons/checklist-16
      #    info: octicons/info-16
      #    tip: octicons/squirrel-16
      #    success: octicons/check-16
      #    question: octicons/question-16
      #    warning: octicons/alert-16
      #    failure: octicons/x-circle-16
      #    danger: octicons/zap-16
      #    bug: octicons/bug-16
      #    example: octicons/beaker-16
      #    quote: octicons/quote-16

    palette:

      #- media: "(prefers-color-scheme)"
      #  toggle:
      #    icon: material/weather-night
      #    name: Switch to dark mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: green
        accent: deep orange
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: green
        accent: deep orange
        toggle: 
          icon: material/lightbulb-on
          name: Switch to light mode

extra_css: 
  - stylesheets/extra.css
  - stylesheets/link_embeds.css

markdown_extensions:
  - tables
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

