site_name: AHO Open Source
site_url: https://aho-opensource.github.io
site_description: Freedom for The Oslo School of Architecture and Design
site_author: karamellpelle
repo_url: https://github.com/aho-opensource/homepage
repo_name: aho-opensource/homepage

nav:
  - index.md
  - "Software":
      - "System":   software#system
      - "CAD":      software#cad
      - "Graphic":  software#graphic
      - "Video":    software#video
      - "Audio":    software#audio
      - "Web":      software#web
      - "Office":   software#office
      - "Diagram":  software#diagram
      - "Tools":    software#tools
  - "Assets":
    - "Icons": assets#icons
    - "Fonts": assets#fonts
    - "Vectors": assets#vectors
    - "3D-models": assets#3d-models
    - "Textures": assets#textures
    - "Photos": assets#photos
    - "Sound": assets#sound
    - "Music": assets#music
    - "Data": assets#data
    #- "": assets#
  - "Study Programs":
    - programmes/architecture.md
    - programmes/design.md
    - programmes/landscape_architecture.md
  #- about.md
  #- todo.md

plugins:
  - search
  - tags
  #- meta # this is not Materials Insider anymore, so add this soon

#extra:  

theme:
    name: material

    logo: images/ahopen-logo.svg
    favicon: images/ahopen-favicon.svg

    features:
        - content.tabs.link # link tab selection on page
        - navigation.footer
        - navigation.tracker
        #- navigation.expand
        - toc.follow
        #- navigation.indexes

    icon:
      annotation: material/tooltip-text

      #admonition:
      #    note: octicons/tag-16
      #    abstract: octicons/checklist-16
      #    info: octicons/info-16
      #    tip: octicons/squirrel-16
      #    success: octicons/check-16
      #    question: octicons/question-16
      #    warning: octicons/alert-16
      #    failure: octicons/x-circle-16
      #    danger: octicons/zap-16
      #    bug: octicons/bug-16
      #    example: octicons/beaker-16
      #    quote: octicons/quote-16

    palette:

      #- media: "(prefers-color-scheme)"
      #  toggle:
      #    icon: material/weather-night
      #    name: Switch to dark mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: green
        accent: deep orange
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: green
        accent: deep orange
        toggle: 
          icon: material/lightbulb-on
          name: Switch to light mode

extra_css: 
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

